### ISSUE TITLE
Fix weird failing tests at travis-ci

### ISSUE THREAD

**Issue by nichtich** [scriptotek/mc2skos#27]
I run exactly the same version as release 0.4.0 at travis-ci. This was passing 21 days ago:

https://travis-ci.org/scriptotek/mc2skos/builds/192751396

but now it fails:

https://travis-ci.org/gbv/mc2skos/builds/199175954

The error is caused by

tests/test_process_record.py::TestRecord::testSynthesizedNumberComponentsIncludingAddTable

which should be skipped but it isn't.

This does not seem to be the only weird fail at travis-ci. This build even fails to install although no crucial changes are included:

https://travis-ci.org/gbv/mc2skos/builds/199180795

Maybe this is cause by some caching or installation problems at travis-ci?

**Comment by danmichaelo** [comment]
The latter one is really strange. It almost seems like setuptools finds the wrong package!!

```
Searching for rdflib
Downloading https://pypi.python.org/packages/ba/48/edaad22fc9de34500699f0c7fc9124385dd425fd18857244f126a6f7df66/rdflib-jsonld-0.4.0.tar.gz#md5=69097f57d302791a2959c07e110c47cf
Best match: rdflib jsonld-0.4.0
```

On stackoverflow I found [this](http://stackoverflow.com/questions/27497470/setuptools-finds-wrong-package-during-install).

And indeed, adding `rdflib` to `setup_requires` helped… Not a very satisfying solution though since it's only a workaround for some unknown underlying problem..
